### ISSUE TITLE
404: gluten flour

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Grimgrains#11]
In the [flour](https://grimgrains.com/#flour) page, a similar ingredient is gluten flour. However, clicking the link leads to a 404 page, and `ingredients.ndtl` has no entry for it.

Gluten flour listed (just before end of list):
![Screenshot showing gluten flour](https://user-images.githubusercontent.com/7029204/59971611-695f4480-95d3-11e9-8e53-300da1a50a6e.png)

404 page:
![gluten flour 404](https://user-images.githubusercontent.com/7029204/59971619-7c721480-95d3-11e9-941d-1e13b92a4fea.png)

**Comment by microlith57** [comment]
I assume that the fix is as simple as creating an entry in `ingredients.ndtl` for it. I will do this when #12 and #14 are closed.

**Comment by neauoire** [comment]
Yeah, that'll fix it.
