### ISSUE TITLE
[Suggestion] Sub-ingredient lists

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Grimgrains#13]
I suggest that for ingredients such as flour, a list of sub-ingredients should be shown (eg. all purpose, wholewheat, einkorn, etc.) and in these sub-ingredients' pages a link would take you back up.

This could be implemented a bit like in Paradise - a `Parent` ingredient for each ingredient, which can be blank, and then autogenerate everything from there.

**Comment by neauoire** [comment]
It would be nice to automatically handle this parenting, maybe the search similarity function might be able to do this.

**Comment by microlith57** [comment]
Possibly, but I didn't do this because then ingredients such as Nori wouldn't automatically be siblings of Bull Kelp Powder (both being seaweed products).
