### ISSUE TITLE
[Suggestion] Separate sauces into new recipes

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Grimgrains#15]
These sauces could be useful, and I think it may be good to add recipes for them.

Relevant line: [`recipes.ndtl#127`](https://github.com/hundredrabbits/Grimgrains/blob/17491e9b827b351bae59d47f3b32ada9467a4485/scripts/database/recipes.ndtl#L127)

**Comment by rekkabell** [comment]
I will think about this :>

**Comment by rekkabell** [comment]
I've started to make separate recipes for sauces. There are two so far: Tzaziki and Veganaise. There will be more, thanks again for the great suggestion.
