### ISSUE TITLE
License not clear on website

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Grimgrains#18]
In the About page, it is stated that the content of Grimgrains is copyright with all rights reserved.

Perhaps it would be good to replace this with the MIT license terms as this is Grimgrains' license? The wording is technically true as is, but it would help if the MIT terms were explicitly stated / referenced.

**Comment by neauoire** [comment]
I agree, the graphical assets are all right reserved, the code is MIT. I'll make that clear after we merge the PRs.
