### ISSUE TITLE
[Note] Corn dumplings can be made with added turmeric

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Grimgrains#19]
I once added around `1-2 tsp` of turmeric to my dumplings when I made them (with your recipe, but using a 50/50 mix of wholewheat and plain flour) and they emerged with red centres! The turmeric was leeched out of the outer parts of each dumpling, but the middle was a beautiful red.

Unfortunately I haven't replicated this, but if I get a consistent recipe I will update these numbers and potentially open a PR.

**Comment by neauoire** [comment]
We will try the recipe with turmeric this week 👍

**Comment by neauoire** [comment]
It might not be added as an ingredient, but could do with a mention in the description.

**Comment by rekkabell** [comment]
Oh! Turmeric turns red when mixed with an alkali, so maybe it's because of the baking soda? Interesting. I do tend to add turmeric to recipes often, I can certainly suggest it in the description, but yea, it's not a necessary ingredient.
