### ISSUE TITLE
Page jump

### ISSUE THREAD

**Issue by rekkabell** [hundredrabbits/Grimgrains#26]
Enable page jump, for nutrition page, or other pages with a lot of content.

**Comment by microlith57** [comment]
This can't be done via `#` links but a workaround is via the [`element.scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) function.
I can add this in my next PR :)

**Comment by neauoire** [comment]
I'm not entirely sure that we do need the jump script after all.
I'm looking forward to merging those changes, I think we'll gradually phase out Riven these next couple of weeks and just use a simpler way to manage routing.
