### ISSUE TITLE
[technical] `href='#...'` vs. `onclick='Ø...'` vs. `href='javascript:Ø...'`

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Grimgrains#27]
I am working on a PR (#28) for better accessibility and found that links with only `onclick` attributes can't be selected using the tab key, so `href` is probably better.
However, lots of links in Grimgrains look like this:
```html
<a href='#${name.to_url()}' onclick="Ø('query').bang('${name}')">
...
</a>
```
([scripts/templates/home.js:63](https://github.com/hundredrabbits/Grimgrains/blob/master/scripts/templates/home.js#L63))

This seems redundant; having only one of the two works OK for me (but I haven't tested all links).
Perhaps it would be a good idea to switch to either
```html
<a href='#${name.to_url()}'>
...
</a>
```

or
```html
<a href="javascript:Ø('query').bang('${name}')">
...
</a>
```

**Comment by neauoire** [comment]
That PR broke most of the links of the site, but I'll bring them back and close the issue once I'm done.
