### ISSUE TITLE
Veganaise page recipe link doesn't work

### ISSUE THREAD

**Issue by ftrvxmtrx** [hundredrabbits/Grimgrains#36]
https://grimgrains.com/site/veganaise.html doesn't seem to link to the recipe properly and contains info about tofu, idk if that's intentional.

**Comment by neauoire** [comment]
Fixed in https://github.com/hundredrabbits/Grimgrains/commit/24ac22431425dfee0fbf45e10ee2b7800ea72521

Thanks Sigrid
