### ISSUE TITLE
'undefined' page

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Grimgrains#4]
When visiting a page which does not exist - https://grimgrains.com/#this+page+does+not+exist - the page loaded has a title of `undefined`, and no content.
Perhaps this edge case could be detected and redirected to a 404 page?

Example (Google Chrome on Chromebook):
![an 'undefined' page](https://user-images.githubusercontent.com/7029204/59166566-32bf0e00-8b7f-11e9-8657-59afd5ad46ba.png)

**Comment by microlith57** [comment]
@neauoire It seems that wiki.xxiivv.com has a page-not-found page which works (see: https://wiki.xxiivv.com/#not+a+real+page).
Any insight into how this works?

**Comment by neauoire** [comment]
I've done an [implementation to grimgrains](https://github.com/hundredrabbits/Grimgrains/commit/818c03c70b0ed0542957cc97cd0b61fb570b9265) like the one on XXIIVV :)
