### ISSUE TITLE
Accessibility Issues

### ISSUE THREAD

**Issue by Thomasorus** [hundredrabbits/Grimgrains#46]
Hello here!

Grimgrains has small accessibility issues that are quite easy to fix. 

Important issues:

1. Provide a visible focus on links with images
Problem: The website has an `outline:none` rule on the html tag that makes using tab for navigating interactive elements (like links) impossible.
Solution: remove `outline:none` to let the native browser focus style work. Or style it in a way that is close to the text links that goes from an solid underline to a dotted underline.

2. No h2 on homepage. 
Problem: There are two h1 on the home page and several h3, but no h2. 
Solution: Ingredients and Recipes should be h2 and another h1 should be before them. 

Less important / cosiness issues:

3. <br><br> are vocalized as "blank"
Problem: Several recipes use <br><br> for line breaks but nvda on firefox vocalizes it as "blank". 
Solution: on one of the br (or all of them actually) add an aria-hidden true: `<br aria-hidden="true">`

4. Double links in the list of ingredients
Problem: When navigating with nvda + firefox (ex: https://grimgrains.com/site/black_sesame_brittle.html), the list of ingredients is vocalized two times as they are two texts inside the link. It says "link brown sugar" and "link 45g".
Solution: put the quantity outside of the link while keeping it in <dt>

Please ask if you have any question!

**Comment by neauoire** [comment]
Could you have a look and tell me if 1, 2 and 4 have been improved?

**Comment by Thomasorus** [comment]
1, 2 and 4 are ok!

**Comment by rekkabell** [comment]
Fixed 3 also :>.
