### ISSUE TITLE
Use browser native lazy-loading

### ISSUE THREAD

**Issue by Thomasorus** [hundredrabbits/Grimgrains#47]
Hello!

Problem: Grimgrains loads 4.64mo of images on the homepage for the 247 ingredients listed. It makes the page too heavy to load on small connection when loaded for the first time.
Solution: It would be easier for slow connections to lazy-load those images using the `loading="lazy"` attribute on images. This way browsers who support this feature will only load images in the viewport, which will result in less data to load and see the top of the website.

Thanks!

**Comment by neauoire** [comment]
Added with https://github.com/hundredrabbits/Grimgrains/commit/d119fc90e0b6795774c2fb83bcdd76c2b65494fa
