### ISSUE TITLE
Broken link for japanese rice vinegar in a couple recipes

### ISSUE THREAD

**Issue by SylvanSign** [hundredrabbits/Grimgrains#54]
On these two recipes:
- https://grimgrains.com/site/roasted_carrots_with_beluga_lentils.html
- https://grimgrains.com/site/sweet_mock_eel_nigiri.html

they each have a broken link to
- https://grimgrains.com/site/Japanese_rice_vinegar.html

where it seems that the capital `J` should instead be a lowercase `j` to fix the link:
- https://grimgrains.com/site/japanese_rice_vinegar.html

**Comment by rekkabell** [comment]
Yep, you are very right. Don't know why I put a capital J on those links :/. Fixed. Thank you for reporting it :>
