### ISSUE TITLE
Pumpkin typo/formatting error

### ISSUE THREAD

**Issue by Dakedres** [hundredrabbits/Grimgrains#64]
I found this strange typo on the page for [pumpkins](https://grimgrains.com/site/pumpkin.html) 

> Pumpkins are also cultivated for their[ and oils.](http://grimgrains.com/site/pumpkin_seeds.html)

**Comment by rekkabell** [comment]
Ah! Yes. There's supposed to be a link there to pumpkin_seeds.html, but I forgot to close the link tag ;)... its not been fixed!
